apiVersion: v1
kind: Service #Sub-Type으로 ClusterIP,NodePort,LoadBalancer,Ingress가 존재
metadata:
  name: client-node-port
spec:
  type: NodePort #container의 port를 외부에 공개, Dev환경에서 주로 사용
  ports:
    - port: 3050 # 다른 Object에서 접근 시 사용하는 port
      targetPort: 3000 # service에서 target에 forwarding할 때 보내는 port
      nodePort: 31515 # 외부에서 접근 시 사용하는 port 항상(30000-32767 사이에 존재)
  selector: #Object label 중 아래 key:value에 해당하는 곳에 위 port에 req가 오면 전달
    component: web
