name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./complex
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t saehoon/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true saehoon/react-test npm test

      - run: docker build -t saehoon0501/multi-client ./client
      - run: docker build -t saehoon0501/multi-nginx ./nginx
      - run: docker build -t saehoon0501/multi-server ./server
      - run: docker build -t saehoon0501/multi-worker ./worker

      - run: docker push saehoon0501/multi-client
      - run: docker push saehoon0501/multi-nginx
      - run: docker push saehoon0501/multi-server
      - run: docker push saehoon0501/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          bucket_path: "docker-multi"
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-client
          environment_name: Multi-client-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-104625403644
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: ./complex/deploy.zip
          wait_for_environment_recovery: 60
